name: CI Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: awgman
            artifact_name: awgman-linux-amd64

          # macOS 
          - os: macos-latest
            target: aarch64-apple-darwin
            bin_name: awgman
            artifact_name: awgman-macos-arm64

          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: awgman.exe
            artifact_name: awgman-windows-amd64.exe
    steps:
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cross linker (Linux aarch64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Setup toolchain
        run: rustup toolchain install stable --target ${{ matrix.target }} --profile minimal && rustup default stable
      - name: Build with Cargo
        run: cargo build --release --bin awgman --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.bin_name }}
